### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Veradictus** [Oman395/godot-better-lighting-2d#1]
This is perhaps the closest shader to what I need, however when trying to use it in a tile-based game it ended up crippling the performance. Tweaking the shader parameters to the point performance isn't hindered makes it look far too choppy. Any way to optimize this further?

**Comment by Oman395** [comment]
Closing as completed after a decent amount of work in DMs and a couple patches, though mostly not performance related-- for future reference, this issue was caused by lights being too large (and therefore most tiles needing to calculate lighting for all the visible lights, causing some performance issues).
