### ISSUE TITLE
fake radius ?

### ISSUE THREAD

**Issue by demolen** [Oman395/godot-better-lighting-2d#2]
"Individual lights can't have individual settings, such as radius; unfortunately, there's just not very much available to me in the light() function for each light. I could create a global array uniform, but I find that clunky, so for now I'm using this simplified system-- if enough people request, I might make a global array option.is:issue is:open "

wouldn't using a radial gradient for the light simply achieve the same thing as light radius?

**Comment by Oman395** [comment]
Yes and no. While yes, this would achieve the desired result of the light looking correct without shadows, the issue comes when you're trying to create shadows-- essentially, the "hack" I'm using to get the shadows looking good while only casting 1 ray per light source requires that the radius of the light source be known; if all you care about is the look on the ground, however, using a gradient would be more than sufficient-- but this would also require light fade to be disabled, and you would need to create a light texture for every single light (rather than just not needing to, which is one of the reasons I made this shader in the first place)
